
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Cellular Laboratory
 */
public class cover extends javax.swing.JFrame {

    /**
     * Creates new form cover
     */
    public cover() {
        initComponents();
        register.setVisible(false);
        nama.setVisible(false);
        play.setVisible(false);
        abouttext.setVisible(false);
        cancel.setVisible(false);
        layoutcarabermain.setVisible(false);
        placeholder.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        layoutcarabermain = new javax.swing.JLabel();
        abouttext = new javax.swing.JLabel();
        placeholder = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        play = new javax.swing.JButton();
        register = new javax.swing.JLabel();
        mulai = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        carabermain = new javax.swing.JButton();
        about = new javax.swing.JButton();
        cover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEBAK LAGU");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        cancel.setBorder(null);
        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        layoutcarabermain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layoutcarabermain.png"))); // NOI18N
        layoutcarabermain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                layoutcarabermainMouseClicked(evt);
            }
        });
        jPanel1.add(layoutcarabermain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        abouttext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abouttext.png"))); // NOI18N
        abouttext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abouttextMouseClicked(evt);
            }
        });
        jPanel1.add(abouttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        placeholder.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        placeholder.setForeground(new java.awt.Color(204, 204, 204));
        placeholder.setText("Masukan Nama Anda");
        placeholder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placeholderMouseClicked(evt);
            }
        });
        placeholder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeholderKeyTyped(evt);
            }
        });
        jPanel1.add(placeholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 390, 90));

        nama.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nama.setToolTipText("");
        nama.setBorder(null);
        nama.setFocusCycleRoot(true);
        nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaMouseClicked(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaKeyTyped(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 390, 90));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
        play.setBorder(null);
        play.setBorderPainted(false);
        play.setContentAreaFilled(false);
        play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jPanel1.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nama.png"))); // NOI18N
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        mulai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULAI.png"))); // NOI18N
        mulai.setBorder(null);
        mulai.setBorderPainted(false);
        mulai.setContentAreaFilled(false);
        mulai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulaiMouseClicked(evt);
            }
        });
        jPanel1.add(mulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keluar.png"))); // NOI18N
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        carabermain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CARA BERMAIN.png"))); // NOI18N
        carabermain.setBorder(null);
        carabermain.setBorderPainted(false);
        carabermain.setContentAreaFilled(false);
        carabermain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carabermain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carabermainMouseClicked(evt);
            }
        });
        jPanel1.add(carabermain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png"))); // NOI18N
        about.setBorder(null);
        about.setBorderPainted(false);
        about.setContentAreaFilled(false);
        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jPanel1.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, -1, -1));

        cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0.png"))); // NOI18N
        cover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coverMouseClicked(evt);
            }
        });
        jPanel1.add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(708, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulaiMouseClicked
        // TODO add your handling code here:
        register.setVisible(true);
        placeholder.setVisible(true);
        nama.setVisible(true);
        play.setVisible(true);
        mulai.setVisible(false);
        carabermain.setVisible(false);
        exit.setVisible(false);
        nama.grabFocus();
        if(nama.getText().equals("")){
            placeholder.setVisible(true);
        }else{
            placeholder.setVisible(false);
        }
    }//GEN-LAST:event_mulaiMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        int pil;
        pil = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin keluar dari aplikasi ini ?", "Keluar Game", JOptionPane.YES_NO_OPTION);
        if (pil == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void carabermainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carabermainMouseClicked
        // TODO add your handling code here:        
        mulai.setVisible(false);
        carabermain.setVisible(false);
        exit.setVisible(false);
        layoutcarabermain.setVisible(true);
        cancel.setVisible(true);
    }//GEN-LAST:event_carabermainMouseClicked

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        // TODO add your handling code here:
        if (nama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Anda Harus Mengisikan Nama Terlebih Dahulu");
        } else {
            stage1 obj = new stage1(nama.getText());
            this.setVisible(false);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_playMouseClicked

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        abouttext.setVisible(false);
        layoutcarabermain.setVisible(false);
        cancel.setVisible(false);
        mulai.setVisible(true);
        carabermain.setVisible(true);
        exit.setVisible(true);
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        abouttext.setVisible(true);
        cancel.setVisible(true);
    }//GEN-LAST:event_aboutMouseClicked

    private void coverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coverMouseClicked
        // TODO add your handling code here:
        register.setVisible(false);
        play.setVisible(false);
        nama.setVisible(false);
        mulai.setVisible(true);
        carabermain.setVisible(true);
        exit.setVisible(true);
        placeholder.setVisible(false);
    }//GEN-LAST:event_coverMouseClicked

    private void abouttextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abouttextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_abouttextMouseClicked

    private void layoutcarabermainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layoutcarabermainMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_layoutcarabermainMouseClicked

    private void namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMouseClicked
        // TODO add your handling code here:
        if(nama.getText().equals("")){
            placeholder.setVisible(true);
        }
    }//GEN-LAST:event_namaMouseClicked

    private void placeholderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeholderMouseClicked
        // TODO add your handling code here:
        nama.grabFocus();
    }//GEN-LAST:event_placeholderMouseClicked

    private void placeholderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeholderKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeholderKeyTyped

    private void namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyPressed
        // TODO add your handling code here:
        if(nama.getText().equals("")){
            placeholder.setVisible(true);
        }else{
            placeholder.setVisible(false);
        }
    }//GEN-LAST:event_namaKeyPressed

    private void namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyReleased
        // TODO add your handling code here:
        if(nama.getText().equals("")){
            placeholder.setVisible(true);
        }else{
            placeholder.setVisible(false);
        }
    }//GEN-LAST:event_namaKeyReleased

    private void namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyTyped
        // TODO add your handling code here:
        if(nama.getText().equals("")){
            placeholder.setVisible(true);
        }else{
            placeholder.setVisible(false);
        }
    }//GEN-LAST:event_namaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JLabel abouttext;
    private javax.swing.JButton cancel;
    private javax.swing.JButton carabermain;
    private javax.swing.JLabel cover;
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel layoutcarabermain;
    private javax.swing.JButton mulai;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel placeholder;
    private javax.swing.JButton play;
    private javax.swing.JLabel register;
    // End of variables declaration//GEN-END:variables
}
